project_id = "gwjdijkbmesjoqmfepkc"

[functions.airtable-proxy]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false

[functions.system-bookings]
verify_jwt = false


[functions.sync-google-calendar]
verify_jwt = false

[functions.import-google-calendar]
verify_jwt = false

[functions.full-sync-google-calendar]
verify_jwt = false
