project_id = "gwjdijkbmesjoqmfepkc"

[functions.airtable-proxy]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false

[functions.system-bookings]
verify_jwt = false

[functions.google-calendar-auth]
verify_jwt = false

[functions.google-calendar-callback]
verify_jwt = false

[functions.sync-google-calendar]
verify_jwt = false
